package cn.ljtnono.wyapp.entity;

import java.util.Date;

public class WyImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_image.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_image.image_url
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_image.image_upload_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date imageUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_image.image_modify_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date imageModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyImage(String id, String imageUrl, Date imageUploadTime, Date imageModifyTime) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.imageUploadTime = imageUploadTime;
        this.imageModifyTime = imageModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyImage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_image.id
     *
     * @return the value of wy_image.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_image.id
     *
     * @param id the value for wy_image.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_image.image_url
     *
     * @return the value of wy_image.image_url
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_image.image_url
     *
     * @param imageUrl the value for wy_image.image_url
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_image.image_upload_time
     *
     * @return the value of wy_image.image_upload_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getImageUploadTime() {
        return imageUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_image.image_upload_time
     *
     * @param imageUploadTime the value for wy_image.image_upload_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setImageUploadTime(Date imageUploadTime) {
        this.imageUploadTime = imageUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_image.image_modify_time
     *
     * @return the value of wy_image.image_modify_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getImageModifyTime() {
        return imageModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_image.image_modify_time
     *
     * @param imageModifyTime the value for wy_image.image_modify_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setImageModifyTime(Date imageModifyTime) {
        this.imageModifyTime = imageModifyTime;
    }
}