package cn.ljtnono.wyapp.entity;

public class WyLawyer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.laywer_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String laywerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.institution
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.server_area
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer serverArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.domain
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_lawyer.service_addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String serviceAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyLawyer(String id, String userId, String laywerId, String institution, Integer serverArea, Integer domain, String serviceAddr) {
        this.id = id;
        this.userId = userId;
        this.laywerId = laywerId;
        this.institution = institution;
        this.serverArea = serverArea;
        this.domain = domain;
        this.serviceAddr = serviceAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyLawyer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.id
     *
     * @return the value of wy_lawyer.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.id
     *
     * @param id the value for wy_lawyer.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.user_id
     *
     * @return the value of wy_lawyer.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.user_id
     *
     * @param userId the value for wy_lawyer.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.laywer_id
     *
     * @return the value of wy_lawyer.laywer_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getLaywerId() {
        return laywerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.laywer_id
     *
     * @param laywerId the value for wy_lawyer.laywer_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setLaywerId(String laywerId) {
        this.laywerId = laywerId == null ? null : laywerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.institution
     *
     * @return the value of wy_lawyer.institution
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.institution
     *
     * @param institution the value for wy_lawyer.institution
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setInstitution(String institution) {
        this.institution = institution == null ? null : institution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.server_area
     *
     * @return the value of wy_lawyer.server_area
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getServerArea() {
        return serverArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.server_area
     *
     * @param serverArea the value for wy_lawyer.server_area
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setServerArea(Integer serverArea) {
        this.serverArea = serverArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.domain
     *
     * @return the value of wy_lawyer.domain
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.domain
     *
     * @param domain the value for wy_lawyer.domain
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_lawyer.service_addr
     *
     * @return the value of wy_lawyer.service_addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getServiceAddr() {
        return serviceAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_lawyer.service_addr
     *
     * @param serviceAddr the value for wy_lawyer.service_addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setServiceAddr(String serviceAddr) {
        this.serviceAddr = serviceAddr == null ? null : serviceAddr.trim();
    }
}