package cn.ljtnono.wyapp.entity;

import java.util.Date;

public class WyPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_permission.permission_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_permission.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_permission.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyPermission(Integer id, String permissionName, String description, Date createTime) {
        this.id = id;
        this.permissionName = permissionName;
        this.description = description;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyPermission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_permission.id
     *
     * @return the value of wy_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_permission.id
     *
     * @param id the value for wy_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_permission.permission_name
     *
     * @return the value of wy_permission.permission_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_permission.permission_name
     *
     * @param permissionName the value for wy_permission.permission_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_permission.description
     *
     * @return the value of wy_permission.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_permission.description
     *
     * @param description the value for wy_permission.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_permission.create_time
     *
     * @return the value of wy_permission.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_permission.create_time
     *
     * @param createTime the value for wy_permission.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}