package cn.ljtnono.wyapp.entity;

import java.util.Date;

public class WyRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role.role_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyRole(Integer id, String roleName, Date createTime, String description) {
        this.id = id;
        this.roleName = roleName;
        this.createTime = createTime;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role.id
     *
     * @return the value of wy_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role.id
     *
     * @param id the value for wy_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role.role_name
     *
     * @return the value of wy_role.role_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role.role_name
     *
     * @param roleName the value for wy_role.role_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role.create_time
     *
     * @return the value of wy_role.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role.create_time
     *
     * @param createTime the value for wy_role.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role.description
     *
     * @return the value of wy_role.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role.description
     *
     * @param description the value for wy_role.description
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}