package cn.ljtnono.wyapp.entity;

public class WyRolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role_permission.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role_permission.permission_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_role_permission.permission_type
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer permissionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyRolePermission(Integer id, Integer roleId, Integer permissionId, Integer permissionType) {
        this.id = id;
        this.roleId = roleId;
        this.permissionId = permissionId;
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyRolePermission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role_permission.id
     *
     * @return the value of wy_role_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role_permission.id
     *
     * @param id the value for wy_role_permission.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role_permission.role_id
     *
     * @return the value of wy_role_permission.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role_permission.role_id
     *
     * @param roleId the value for wy_role_permission.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role_permission.permission_id
     *
     * @return the value of wy_role_permission.permission_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role_permission.permission_id
     *
     * @param permissionId the value for wy_role_permission.permission_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_role_permission.permission_type
     *
     * @return the value of wy_role_permission.permission_type
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_role_permission.permission_type
     *
     * @param permissionType the value for wy_role_permission.permission_type
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setPermissionType(Integer permissionType) {
        this.permissionType = permissionType;
    }
}