package cn.ljtnono.wyapp.entity;

public class WyUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user_role.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user_role.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyUserRole(Integer id, Integer roleId, String userId) {
        this.id = id;
        this.roleId = roleId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyUserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user_role.id
     *
     * @return the value of wy_user_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user_role.id
     *
     * @param id the value for wy_user_role.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user_role.role_id
     *
     * @return the value of wy_user_role.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user_role.role_id
     *
     * @param roleId the value for wy_user_role.role_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user_role.user_id
     *
     * @return the value of wy_user_role.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user_role.user_id
     *
     * @param userId the value for wy_user_role.user_id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}