package cn.ljtnono.wyapp.entity;

import java.util.Date;

public class WyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.tel
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.email
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.login_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.password
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.last_login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wy_user.profile
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    private String profile;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyUser(String id, String name, String tel, String email, String addr, String loginName, String password, Date createTime, Date loginTime, Date lastLoginTime, String profile) {
        this.id = id;
        this.name = name;
        this.tel = tel;
        this.email = email;
        this.addr = addr;
        this.loginName = loginName;
        this.password = password;
        this.createTime = createTime;
        this.loginTime = loginTime;
        this.lastLoginTime = lastLoginTime;
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public WyUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.id
     *
     * @return the value of wy_user.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.id
     *
     * @param id the value for wy_user.id
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.name
     *
     * @return the value of wy_user.name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.name
     *
     * @param name the value for wy_user.name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.tel
     *
     * @return the value of wy_user.tel
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.tel
     *
     * @param tel the value for wy_user.tel
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.email
     *
     * @return the value of wy_user.email
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.email
     *
     * @param email the value for wy_user.email
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.addr
     *
     * @return the value of wy_user.addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.addr
     *
     * @param addr the value for wy_user.addr
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.login_name
     *
     * @return the value of wy_user.login_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.login_name
     *
     * @param loginName the value for wy_user.login_name
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.password
     *
     * @return the value of wy_user.password
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.password
     *
     * @param password the value for wy_user.password
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.create_time
     *
     * @return the value of wy_user.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.create_time
     *
     * @param createTime the value for wy_user.create_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.login_time
     *
     * @return the value of wy_user.login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.login_time
     *
     * @param loginTime the value for wy_user.login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.last_login_time
     *
     * @return the value of wy_user.last_login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.last_login_time
     *
     * @param lastLoginTime the value for wy_user.last_login_time
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wy_user.profile
     *
     * @return the value of wy_user.profile
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wy_user.profile
     *
     * @param profile the value for wy_user.profile
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }
}