package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyImage;
import cn.ljtnono.wyapp.entity.WyImageExample.Criteria;
import cn.ljtnono.wyapp.entity.WyImageExample.Criterion;
import cn.ljtnono.wyapp.entity.WyImageExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class WyImageSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String countByExample(WyImageExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("wy_image");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String deleteByExample(WyImageExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("wy_image");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String insertSelective(WyImage record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("wy_image");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getImageUrl() != null) {
            sql.VALUES("image_url", "#{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getImageUploadTime() != null) {
            sql.VALUES("image_upload_time", "#{imageUploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageModifyTime() != null) {
            sql.VALUES("image_modify_time", "#{imageModifyTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String selectByExample(WyImageExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("image_url");
        sql.SELECT("image_upload_time");
        sql.SELECT("image_modify_time");
        sql.FROM("wy_image");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        WyImage record = (WyImage) parameter.get("record");
        WyImageExample example = (WyImageExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("wy_image");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getImageUrl() != null) {
            sql.SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getImageUploadTime() != null) {
            sql.SET("image_upload_time = #{record.imageUploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageModifyTime() != null) {
            sql.SET("image_modify_time = #{record.imageModifyTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("wy_image");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        sql.SET("image_upload_time = #{record.imageUploadTime,jdbcType=TIMESTAMP}");
        sql.SET("image_modify_time = #{record.imageModifyTime,jdbcType=TIMESTAMP}");
        
        WyImageExample example = (WyImageExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByPrimaryKeySelective(WyImage record) {
        SQL sql = new SQL();
        sql.UPDATE("wy_image");
        
        if (record.getImageUrl() != null) {
            sql.SET("image_url = #{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getImageUploadTime() != null) {
            sql.SET("image_upload_time = #{imageUploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageModifyTime() != null) {
            sql.SET("image_modify_time = #{imageModifyTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    protected void applyWhere(SQL sql, WyImageExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}