package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyImage;
import cn.ljtnono.wyapp.entity.WyImageExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyImageSqlProvider.class, method="countByExample")
    long countByExample(WyImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyImageSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_image",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_image (id, image_url, ",
        "image_upload_time, image_modify_time)",
        "values (#{id,jdbcType=VARCHAR}, #{imageUrl,jdbcType=VARCHAR}, ",
        "#{imageUploadTime,jdbcType=TIMESTAMP}, #{imageModifyTime,jdbcType=TIMESTAMP})"
    })
    int insert(WyImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyImageSqlProvider.class, method="insertSelective")
    int insertSelective(WyImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyImageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="image_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="image_upload_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="image_modify_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<WyImage> selectByExample(WyImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, image_url, image_upload_time, image_modify_time",
        "from wy_image",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="image_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="image_upload_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="image_modify_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    WyImage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyImageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyImage record, @Param("example") WyImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyImageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyImage record, @Param("example") WyImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyImageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_image
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_image",
        "set image_url = #{imageUrl,jdbcType=VARCHAR},",
          "image_upload_time = #{imageUploadTime,jdbcType=TIMESTAMP},",
          "image_modify_time = #{imageModifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WyImage record);
}