package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyLawyer;
import cn.ljtnono.wyapp.entity.WyLawyerExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyLawyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyLawyerSqlProvider.class, method="countByExample")
    long countByExample(WyLawyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyLawyerSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyLawyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_lawyer",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_lawyer (id, user_id, ",
        "laywer_id, institution, ",
        "server_area, domain, ",
        "service_addr)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{laywerId,jdbcType=VARCHAR}, #{institution,jdbcType=VARCHAR}, ",
        "#{serverArea,jdbcType=INTEGER}, #{domain,jdbcType=INTEGER}, ",
        "#{serviceAddr,jdbcType=VARCHAR})"
    })
    int insert(WyLawyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyLawyerSqlProvider.class, method="insertSelective")
    int insertSelective(WyLawyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyLawyerSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="user_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="laywer_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="institution", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="server_area", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="domain", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="service_addr", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<WyLawyer> selectByExample(WyLawyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, user_id, laywer_id, institution, server_area, domain, service_addr",
        "from wy_lawyer",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="user_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="laywer_id", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="institution", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="server_area", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="domain", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="service_addr", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    WyLawyer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyLawyerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyLawyer record, @Param("example") WyLawyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyLawyerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyLawyer record, @Param("example") WyLawyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyLawyerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyLawyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_lawyer",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "laywer_id = #{laywerId,jdbcType=VARCHAR},",
          "institution = #{institution,jdbcType=VARCHAR},",
          "server_area = #{serverArea,jdbcType=INTEGER},",
          "domain = #{domain,jdbcType=INTEGER},",
          "service_addr = #{serviceAddr,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WyLawyer record);
}