package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyLawyer;
import cn.ljtnono.wyapp.entity.WyLawyerExample.Criteria;
import cn.ljtnono.wyapp.entity.WyLawyerExample.Criterion;
import cn.ljtnono.wyapp.entity.WyLawyerExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class WyLawyerSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String countByExample(WyLawyerExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("wy_lawyer");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String deleteByExample(WyLawyerExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("wy_lawyer");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String insertSelective(WyLawyer record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("wy_lawyer");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLaywerId() != null) {
            sql.VALUES("laywer_id", "#{laywerId,jdbcType=VARCHAR}");
        }
        
        if (record.getInstitution() != null) {
            sql.VALUES("institution", "#{institution,jdbcType=VARCHAR}");
        }
        
        if (record.getServerArea() != null) {
            sql.VALUES("server_area", "#{serverArea,jdbcType=INTEGER}");
        }
        
        if (record.getDomain() != null) {
            sql.VALUES("domain", "#{domain,jdbcType=INTEGER}");
        }
        
        if (record.getServiceAddr() != null) {
            sql.VALUES("service_addr", "#{serviceAddr,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String selectByExample(WyLawyerExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("laywer_id");
        sql.SELECT("institution");
        sql.SELECT("server_area");
        sql.SELECT("domain");
        sql.SELECT("service_addr");
        sql.FROM("wy_lawyer");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        WyLawyer record = (WyLawyer) parameter.get("record");
        WyLawyerExample example = (WyLawyerExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("wy_lawyer");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLaywerId() != null) {
            sql.SET("laywer_id = #{record.laywerId,jdbcType=VARCHAR}");
        }
        
        if (record.getInstitution() != null) {
            sql.SET("institution = #{record.institution,jdbcType=VARCHAR}");
        }
        
        if (record.getServerArea() != null) {
            sql.SET("server_area = #{record.serverArea,jdbcType=INTEGER}");
        }
        
        if (record.getDomain() != null) {
            sql.SET("domain = #{record.domain,jdbcType=INTEGER}");
        }
        
        if (record.getServiceAddr() != null) {
            sql.SET("service_addr = #{record.serviceAddr,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("wy_lawyer");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("laywer_id = #{record.laywerId,jdbcType=VARCHAR}");
        sql.SET("institution = #{record.institution,jdbcType=VARCHAR}");
        sql.SET("server_area = #{record.serverArea,jdbcType=INTEGER}");
        sql.SET("domain = #{record.domain,jdbcType=INTEGER}");
        sql.SET("service_addr = #{record.serviceAddr,jdbcType=VARCHAR}");
        
        WyLawyerExample example = (WyLawyerExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    public String updateByPrimaryKeySelective(WyLawyer record) {
        SQL sql = new SQL();
        sql.UPDATE("wy_lawyer");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLaywerId() != null) {
            sql.SET("laywer_id = #{laywerId,jdbcType=VARCHAR}");
        }
        
        if (record.getInstitution() != null) {
            sql.SET("institution = #{institution,jdbcType=VARCHAR}");
        }
        
        if (record.getServerArea() != null) {
            sql.SET("server_area = #{serverArea,jdbcType=INTEGER}");
        }
        
        if (record.getDomain() != null) {
            sql.SET("domain = #{domain,jdbcType=INTEGER}");
        }
        
        if (record.getServiceAddr() != null) {
            sql.SET("service_addr = #{serviceAddr,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_lawyer
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    protected void applyWhere(SQL sql, WyLawyerExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}