package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyPermission;
import cn.ljtnono.wyapp.entity.WyPermissionExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyPermissionSqlProvider.class, method="countByExample")
    long countByExample(WyPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyPermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_permission (id, permission_name, ",
        "description, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{permissionName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(WyPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyPermissionSqlProvider.class, method="insertSelective")
    int insertSelective(WyPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyPermissionSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="permission_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<WyPermission> selectByExample(WyPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, permission_name, description, create_time",
        "from wy_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="permission_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    WyPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyPermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyPermission record, @Param("example") WyPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyPermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyPermission record, @Param("example") WyPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyPermissionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_permission",
        "set permission_name = #{permissionName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WyPermission record);
}