package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyRole;
import cn.ljtnono.wyapp.entity.WyRoleExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyRoleSqlProvider.class, method="countByExample")
    long countByExample(WyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyRoleSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_role (id, role_name, ",
        "create_time, description)",
        "values (#{id,jdbcType=INTEGER}, #{roleName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR})"
    })
    int insert(WyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyRoleSqlProvider.class, method="insertSelective")
    int insertSelective(WyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyRoleSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<WyRole> selectByExample(WyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, role_name, create_time, description",
        "from wy_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    WyRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRoleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyRole record, @Param("example") WyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRoleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyRole record, @Param("example") WyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_role",
        "set role_name = #{roleName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WyRole record);
}