package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyRolePermission;
import cn.ljtnono.wyapp.entity.WyRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyRolePermissionSqlProvider.class, method="countByExample")
    long countByExample(WyRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyRolePermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_role_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_role_permission (id, role_id, ",
        "permission_id, permission_type)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{permissionId,jdbcType=INTEGER}, #{permissionType,jdbcType=INTEGER})"
    })
    int insert(WyRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyRolePermissionSqlProvider.class, method="insertSelective")
    int insertSelective(WyRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyRolePermissionSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="permission_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="permission_type", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<WyRolePermission> selectByExample(WyRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, role_id, permission_id, permission_type",
        "from wy_role_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="permission_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="permission_type", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    WyRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRolePermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyRolePermission record, @Param("example") WyRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRolePermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyRolePermission record, @Param("example") WyRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyRolePermissionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_role_permission
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_role_permission",
        "set role_id = #{roleId,jdbcType=INTEGER},",
          "permission_id = #{permissionId,jdbcType=INTEGER},",
          "permission_type = #{permissionType,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WyRolePermission record);
}