package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyUser;
import cn.ljtnono.wyapp.entity.WyUserExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyUserSqlProvider.class, method="countByExample")
    long countByExample(WyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_user (id, name, ",
        "tel, email, addr, ",
        "login_name, password, ",
        "create_time, login_time, ",
        "last_login_time, profile)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{tel,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{addr,jdbcType=VARCHAR}, ",
        "#{loginName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{loginTime,jdbcType=TIMESTAMP}, ",
        "#{lastLoginTime,jdbcType=TIMESTAMP}, #{profile,jdbcType=VARCHAR})"
    })
    int insert(WyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyUserSqlProvider.class, method="insertSelective")
    int insertSelective(WyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyUserSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tel", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="email", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="addr", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="login_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="login_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="last_login_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="profile", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<WyUser> selectByExample(WyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, name, tel, email, addr, login_name, password, create_time, login_time, last_login_time, ",
        "profile",
        "from wy_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tel", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="email", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="addr", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="login_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="login_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="last_login_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="profile", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    WyUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyUser record, @Param("example") WyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyUser record, @Param("example") WyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "addr = #{addr,jdbcType=VARCHAR},",
          "login_name = #{loginName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "login_time = #{loginTime,jdbcType=TIMESTAMP},",
          "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
          "profile = #{profile,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WyUser record);
}