package cn.ljtnono.wyapp.mapper;

import cn.ljtnono.wyapp.entity.WyUserRole;
import cn.ljtnono.wyapp.entity.WyUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WyUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyUserRoleSqlProvider.class, method="countByExample")
    long countByExample(WyUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @DeleteProvider(type=WyUserRoleSqlProvider.class, method="deleteByExample")
    int deleteByExample(WyUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Delete({
        "delete from wy_user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Insert({
        "insert into wy_user_role (id, role_id, ",
        "user_id)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR})"
    })
    int insert(WyUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @InsertProvider(type=WyUserRoleSqlProvider.class, method="insertSelective")
    int insertSelective(WyUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @SelectProvider(type=WyUserRoleSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="user_id", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<WyUserRole> selectByExample(WyUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Select({
        "select",
        "id, role_id, user_id",
        "from wy_user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="role_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="user_id", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    WyUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserRoleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WyUserRole record, @Param("example") WyUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserRoleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WyUserRole record, @Param("example") WyUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @UpdateProvider(type=WyUserRoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WyUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_user_role
     *
     * @mbg.generated Tue May 28 14:49:24 CST 2019
     */
    @Update({
        "update wy_user_role",
        "set role_id = #{roleId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WyUserRole record);
}